-- Sample data preview
SELECT *
FROM customer
LIMIT 20;

-- Q1. What is the total revenue generated?
SELECT 
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer;

-- Q2. What is the total revenue generated by male vs. female customers?
SELECT 
    gender,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY gender;

-- Q3. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND purchase_amount > (
        SELECT AVG(purchase_amount)
        FROM customer
  );

-- Q4. Which are the top 5 products with the highest average review ratings?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS average_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_review_rating DESC
LIMIT 5;

-- Q5. How does the average purchase amount differ between Standard and Express shipping methods?
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- Q6. How do subscribed and non-subscribed customers compare in terms of average spend and total revenue?
SELECT 
    subscription_status,
    ROUND(AVG(purchase_amount), 2) AS average_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status;

-- Q7. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
        / COUNT(*),
        2
    ) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q8. Segment customers into New, Returning, and Loyal based on purchase history
-- and show the count of each segment
WITH customer_type AS (
    SELECT 
        customer_id,
        CASE
            WHEN previous_purchases = 0 THEN 'New'
            WHEN previous_purchases BETWEEN 1 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS customer_count
FROM customer_type
GROUP BY customer_segment;

-- Q9. What are the top 3 most purchased products within each product category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q10. Are repeat buyers (customers with more than 5 previous purchases)
-- more likely to be subscribed?
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_customer_count
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q11. What is the revenue contribution of each age group?
SELECT 
    age_group,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;